### ISSUE TITLE
Files written to the file-system are lost after update

### ISSUE THREAD

**Issue by shiv19** [EddyVerbruggen/nativescript-app-sync#20]
We noticed that after an AppSync update, the files that the app writes to the file system are lost.
However, things stored in App-Settings remain intact.

**Comment by EddyVerbruggen** [comment]
Hmm, interesting one. Can you tell me how you wrote to the fs (a snippet would be helpful) and which platforms are affected?

**Comment by shiv19** [comment]
```js
import { knownFolders } from 'tns-core-modules/file-system';
const documents = knownFolders.documents();
const jsonFile = documents.getFile('/app/something.json');
jsonFile.readText().then(function(content) {}); // for read
jsonFile.writeText(text).then(function() {}); // for write
```

Something like this. And I realize that files are being written into app folder in this app.

**Comment by shiv19** [comment]
@EddyVerbruggen I believe this affects both Android and iOS since the files are in app folder.
But I haven't tested it on iOS

**Comment by EddyVerbruggen** [comment]
Thanks for the snippet. Looking at this today and reporting my findings here. Note that an iOS sim and device behave differently, so that's why I'll test both of those separately.

- [x] iOS Simulator* ✅
- [ ] iOS Device
- [ ] Android Device

**Comment by EddyVerbruggen** [comment]
Hey @shiv19, can you please give version 1.0.2 a try?

On Android (only) I used to rename the `/app` folder to `/app_backup` and then rename the folder with the pending update to `/app`. So that's why files saved to `/app` were lost. I guess if you save to different folders there wouldn't be an issue.

I've now updated the algorithm to instead copy the new files over the current `/app` folder, so anything already there won't be removed.

**Comment by shiv19** [comment]
Thanks @EddyVerbruggen 
I'll give it a try today :)

**Comment by shiv19** [comment]
@EddyVerbruggen It worked! :D Thank you

**Comment by EddyVerbruggen** [comment]
Woohoo, thx for testing this!
