### ISSUE TITLE
Download error: Error: Could not access local package. Error: The request timed out.

### ISSUE THREAD

**Issue by shiv19** [EddyVerbruggen/nativescript-app-sync#24]
Getting a Download error when trying app-sync on iOS.
Is there any additional configuration required?

We're not whitelisting any domains on Info.plist

Update: AppSync worked on iOS Simulator

On a subsequent launch, I did not get any download error on the device,
I got `AppSync: up to date`, but the app still showed an older version.

Update: On the simulator, the AppSync works, but HMR livesyncs don't work anymore.
On the device, the hmr livesyncs work fine, but the AppSync doesn't work.

If there is any more info required to debug this, please let me know :)

Update: Just noticed that even on Android, I'm unable to use HMR Livesyncs while using AppSync plugin. AppSync's version always prevails

**Comment by shiv19** [comment]
Update: AppSync worked on iOS Simulator

**Comment by EddyVerbruggen** [comment]
Hi, it's normal for HMR/LiveSync not working since AppSync works off a different folder than LiveSync expects to find the app. But I don't consider that a big issue since production apps don't use LiveSync anyway. It's just something to keep in mind (perhaps this should be added to the readme).

You mentioned not having whitelisted anything, but if you haven't whitelisted any other endpoints either I assume you don't restrict any Internet access for your app, so that shouldn't matter.

Wondering if this download error is structural, or perhaps a networking hickup at the time and the plugin should harden against it. With the two demo apps in this repo I don't get a download error on an iOS device. Would it be possible to add the actual error/stacktrace to this issue?

**Comment by shiv19** [comment]
I'll keep an eye out for it.
If I see it again, I'll grab the stack trace for you :)

**Comment by EddyVerbruggen** [comment]
Cool. I'm going to assume it's a network hiccup. The error originates from `"tns-core-modules/http"`'s `getFile` function. So I'll add a simply retry mechanism to harden it a little.

**Comment by shiv19** [comment]
Maybe there should be an easy way to turn AppSync on/off, so that while developing, Devs can use HMR, and while releasing, they can turn on AppSync and then release

**Comment by EddyVerbruggen** [comment]
I like the idea. There are ways to do so though, but nothing explicit at the moment. So for instance, you can simply don't invoke the `.sync` function at all, or don't publish anything to the `Staging` channel, or clear it by running `nativescript-app-sync deployment clear <your app id> Staging`.

**Comment by shiv19** [comment]
Thanks for the idea! I know exactly what to do next :)
